### ISSUE TITLE
好像谷歌翻译并没有工作？

### ISSUE THREAD

**Issue by Key033** [anrgct/utools-saladic#27]
看了一下抓包，发现并没有向谷歌翻译发送请求，软件是把谷歌翻译屏蔽了吗？

**Comment by anrgct** [comment]
以前应该是好的，不知道原因挂了，建议使用浏览器版本或者换个翻译源，暂时不更新了，没啥人用

**Comment by woodwm** [comment]
Saladict v7.20.0 的更新记录里有一条是“更新谷歌翻译”，可能与这个有关系。
https://github.com/crimx/ext-saladict/releases

**Comment by sle1008** [comment]
> 以前应该是好的，不知道原因挂了，建议使用浏览器版本或者换个翻译源，暂时不更新了，没啥人用

我和我身边的人都在用^_^

**Comment by anrgct** [comment]
@woodwm @sle1008 
升级了Saladict v7.20.0后，发现谷歌翻译好了，但有道词典和必应词典又没有了= =，也就没发release，感觉想弃坑了，crimix维护Chrome版的兼容各个网站更新都头大，更何况我这兼容Chrome版的
